name       : threadweaver
version    : 5.47.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/threadweaver-5.47.0.tar.xz : 3fe617cd4c47558326d427b41ce79ba59ea66290cf7e69f47a71e0b7ab598840
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
