name       : threadweaver
version    : 5.101.0
release    : 65
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.101/threadweaver-5.101.0.tar.xz : 4fd103c528590fa974f267d6de5a709b942cee15247b3d877f27d997ff62fbfb
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.tools
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
