name       : threadweaver
version    : 5.70.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.70/threadweaver-5.70.0.tar.xz : 090d477fb26a2148bf915d33edf08a44de49785be466495e088e8e033c073878
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.tools
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
