name       : threadweaver
version    : 5.67.0
release    : 35
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/threadweaver-5.67.0.tar.xz : dba27f3a4238926f6cf3d937b725ef0db06a7e9796058fb037e5177bf10ffd06
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
