name       : threadweaver
version    : 5.68.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.68/threadweaver-5.68.0.tar.xz : e28c0bfff375b3e1e9e4eec72f0a804f3f41c4ec5fd59af9b951708d229eff64
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.tools
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
