name       : threadweaver
version    : 5.79.0
release    : 47
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/threadweaver-5.79.0.tar.xz : 297ca4454e9dc526af8033ee47932a63e3ef3d76868a75dfa66df0f7a04d5918
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.tools
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
