name       : threadweaver
version    : 5.63.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/threadweaver-5.63.0.tar.xz : 4fb56509b42cf02750c063531c981d5a663210e628dd280b7a6c5755ad01497c
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
