name       : threadweaver
version    : 5.41.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.41/threadweaver-5.41.0.tar.xz : 3504d7f97a8f1b3d7180e1cfbf25a270d60875279e53b2e9e523e8d6e0d4d422
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
