name       : threadweaver
version    : 5.71.0
release    : 39
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/threadweaver-5.71.0.tar.xz : 039e73d70f38af38a63235cfb554111ee0d58a6ac168bff0745f0d029c5c528d
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.tools
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
