name       : threadweaver
version    : 5.64.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/threadweaver-5.64.0.tar.xz : 4a3ec0b2b45a5997b24d60059d95006fca5fd86f5d619d8fb1fd30d7510f5a02
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
