name       : threadweaver
version    : 5.48.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/threadweaver-5.48.0.tar.xz : 45840dd049cd4ce6f0562d0bad997b033ee0a5590684f570661436dc9a467a5e
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
