name       : threadweaver
version    : 5.69.0
release    : 37
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/threadweaver-5.69.0.tar.xz : 9db2aaccb48ff7abb2d4338fcafab2dfe0d6038b0b46dd831f6401e5138a2ba7
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.tools
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
