name       : threadweaver
version    : 5.109.0
release    : 69
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.109/threadweaver-5.109.0.tar.xz : 7274529540c4f478519271655a409e4d89c297683eab531a764cf2e5b8c2d2e0
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.tools
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
