name       : threadweaver
version    : 5.61.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.61/threadweaver-5.61.0.tar.xz : e7a0cecfaa60c7a8e4bdd4dfe842fb54a344d331a6c62316c147d8dc2a5e5843
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
