name       : threadweaver
version    : 5.42.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/threadweaver-5.42.0.tar.xz : 76e5bc74ac249358076fafb1d82cab0974fb9ccace9fdaeaf9beffeeeca558c7
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
