name       : threadweaver
version    : 5.32.0
release    : 3
source     :
    - http://download.kde.org/stable/frameworks/5.32/threadweaver-5.32.0.tar.xz : 103c20fa6a024a030a04ee34960e14504663fe41d3cd155db98a348f7f16fee2
license    : LGPL-2.1
component  : programming
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
