name       : threadweaver
version    : 5.87.0
release    : 54
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.87/threadweaver-5.87.0.tar.xz : 904db85af3f4cf5a7b0125264926d83405489feec66cacf675c67019c5fe17bf
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.tools
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
