name       : threadweaver
version    : 5.60.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/threadweaver-5.60.0.tar.xz : 8bf6520e006dadacc82735242500c73810ff3ed4e3053c8352724c9d45f4a122
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
