name       : threadweaver
version    : 5.36.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.36/threadweaver-5.36.0.tar.xz : a15e52811fbc710a618e060c3f7f7cb4623805c83e8a5b24d9f326b55a3be9a7
license    : LGPL-2.1
component  : programming
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
