name       : threadweaver
version    : 5.88.0
release    : 55
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.88/threadweaver-5.88.0.tar.xz : b2f3079158a52c8e49ea0989e18a509dc9693f6a26f0739b133bee0f4b02df1f
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.tools
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
