name       : threadweaver
version    : 5.35.0
release    : 4
source     :
    - https://download.kde.org/stable/frameworks/5.35/threadweaver-5.35.0.tar.xz : 6722459ebafd53d15aaac700a85d20e22bd63a415f990ebaa83fc3ba69c0a39b
license    : LGPL-2.1
component  : programming
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
