name       : threadweaver
version    : 5.43.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/threadweaver-5.43.0.tar.xz : 5d4a33640da357e7a7f101e5a56f2367de4451c3bbd82b63a61cef1ca971b656
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
