name       : threadweaver
version    : 5.91.0
release    : 58
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.91/threadweaver-5.91.0.tar.xz : 22485000cf28d4b28a46e7856532339df5e3e49180ee4a0493f3f3491f9e00a4
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.tools
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
