name       : threadweaver
version    : 5.85.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.85/threadweaver-5.85.0.tar.xz : 431b4a480d200bf12e88ce510efd56edb062eb2284d4233f9602ae62a75da555
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.tools
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
