name       : threadweaver
version    : 5.56.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.56/threadweaver-5.56.0.tar.xz : bd300ce0dc7d8b796fdcc257b9d27eb3f35cdcdef18611a146d3c11f3690dbbf
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
