name       : threadweaver
version    : 5.77.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/threadweaver-5.77.0.tar.xz : 4f898107074943f103fd9d4ee2b82cddcb705382424bd47fcca21b11c167d8f2
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.tools
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
