name       : threadweaver
version    : 5.49.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.49/threadweaver-5.49.0.tar.xz : e77b8681bcac5b990c264ff973c759832362770ee617e171fe2d9c9b04d12b25
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
