name       : threadweaver
version    : 5.51.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/threadweaver-5.51.0.tar.xz : 95f6b2fd7fc94c1d81852c061d5e368bb5c87d5042e34e29ab7aa16ba452aa9d
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
