name       : threadweaver
version    : 5.93.0
release    : 60
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.93/threadweaver-5.93.0.tar.xz : 6c0db7d276052ebc4d512b43792ae2127cb5fafb1cfee890b5f20bd05c06f185
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.tools
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
