name       : threadweaver
version    : 5.96.0
release    : 62
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.96/threadweaver-5.96.0.tar.xz : 78b5cf0b8d5937ac998c3b6f73926bdd483688b758da800126ff0b56f9b25252
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.tools
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
