name       : threadweaver
version    : 5.75.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.75/threadweaver-5.75.0.tar.xz : d082f863fb119e2b98c9e01877b2730eedc0b54392449e3cc9bd54d7803d16ff
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : programming.tools
optimize   : lto
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
