name       : threadweaver
version    : 5.39.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.39/threadweaver-5.39.0.tar.xz : 5c116d93f2ca7bdc75db8d59a4b4852d2c7db48073ad3de21e4bfbf6339a2b80
license    : LGPL-2.1
component  : programming
summary    : Helper for multithreaded programming
description: |
    Helper for multithreaded programming.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
